config:
  send_anonymous_usage_stats: False

tutorial:
  target: dev  # "{{ env_var('TARGET') }}"
  outputs:
    dev:
      type: postgres
      threads: 1
      host: "{{ env_var('DBT_DBHOST') }}"  # e.g. localhost or host.docker.internal
      port: 5432
      user: dbt  # "{{ env_var('DBT_USER') }}"
      pass: password  # "{{ env_var('DBT_PASSWORD') }}"
      dbname: dbt  # "{{ env_var('DBT_DBNAME') }}"
      schema: warehouse  # "{{ env_var('SCHEMA') }}"
